app = "cyclone-client"
primary_region = "iad"

[build]
# Build the static site using the Dockerfile in this folder
  dockerfile = "Dockerfile"
  context = "."

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 50
