services:
  node:
    build:
      context: ./server
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env              # ← add this so Node sees OPENAI_API_KEY, OPENAI_MODEL, etc.
    environment:
      - NODE_ENV=production
      # Optional explicit passthrough (redundant if env_file is present, but harmless):
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - OPENAI_MODEL=${OPENAI_MODEL}
    volumes:
      - ./server/databases:/app/databases
      - ./server/public:/app/public
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  react:
    build:
      context: ./client
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      node:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s