app = "cyclone-server"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"
  context = "."

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 50

[checks]
  [checks.http_check]
    port = 3000
    type = "http"
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "get"
    path = "/api/status"
